### ISSUE TITLE
Missing classes / files

### ISSUE THREAD

**Issue by HendrikPfaff** [riveSunder/carles_game#10]
### Description
I would like to take a look into this competition in this years COG contest, but I have trouble getting started. 

There seem to be some missing classes/files in the current master branch of the repository and thus unexecutable code. From the commit history I can see, that there should be files / classes in the master branch that are nowhere to be found.
The classes `ConvGRNN`,  `CARLA`, `HARLI` and `Agent` are missing. Affected files are:
* notebooks/interactive_evolution.ipynb 
* notebooks/collaborate.ipynb, 
* notebooks/evaluation.ipynb, 
* game_of_carle/agents/toggle.py is missing Agent

### To reproduce
Clone the current master branch of the repo and try to execute the mentioned files.

### Expected behavior
Execution.

**Comment by HendrikPfaff** [comment]
After fiddling around a little bit more. It gets more and more clear to me, that this whole project is not viable at this moment. There're even more missing files and inconsistent references. How is this project, that is supposed to be a judged competition, even remotely supposed to work?

**Comment by riveSunder** [comment]
Hey Bud, 
Thanks for your helpful comments. You'll find the bulk of the notebooks and agents came in on commit bfa064f2e6df31b48a4644e9b29427f4e86d8cfd.
